<?php
namespace App\Features\ServiceOrders\Services;
use App\Core\Enums\MiniTaskStatus;
use App\Core\Enums\ServiceOrderStatus;
use App\Core\Enums\TaskStatus;
use App\Core\Enums\WorkflowType;
use App\Core\Enums\WorkLogStatus;
use App\Core\Helpers\InputSanitizer;
use App\Core\Services\TransactionHandler;
use App\Exceptions\EquipmentUnavailableException;
use App\Exceptions\TaskCreationException;
use App\Features\Equipments\Models\Equipment;
use App\Features\Locations\Models\Location;
use App\Features\MiniTasks\Models\MiniTask;
use App\Features\Sectors\Models\Sector;
use App\Features\ServiceOrders\Events\ServiceOrderCompletedEvent;
use App\Features\ServiceOrders\Events\ServiceOrderCreatedEvent;
use App\Features\ServiceOrders\Models\ServiceOrder;
use App\Features\Tasks\Models\Task;
use App\Features\WorkLogs\Models\WorkLog;
use Illuminate\Http\UploadedFile;
use InvalidArgumentException;
class ServiceOrderService
{
    public function __construct(
        private TransactionHandler $transactions
    ) {}
    
    public function create(array $data, string $managerId): ServiceOrder
    {
        return $this->transactions->execute(function () use ($data, $managerId) {
            $isLoan = ($data['workflow_type'] ?? WorkflowType::STANDARD->value) === WorkflowType::LOAN->value;

            // 1. Create Location (for both workflows)
            $locationId = null;
            if (!empty($data['parish_id'])) {
                $location = Location::create([
                    'parish_id' => $data['parish_id'],
                    'postal_code' => $data['postal_code'] ?? '',
                    'street_address' => InputSanitizer::sanitize($data['street'] ?? ''),
                    'landmark' => isset($data['reference_point']) ? InputSanitizer::sanitize($data['reference_point']) : '',
                    'latitude' => $data['latitude'] ?? null,
                    'longitude' => $data['longitude'] ?? null,
                ]);
                $locationId = $location->id;
            }

            // 2. Handle photo upload
            $photoPath = null;
            if (isset($data['photo']) && $data['photo'] instanceof UploadedFile) {
                $photoPath = $data['photo']->store('service-orders', 'public');
            }

            // 3. CONCURRENT LOAN GUARD — atomic validation + status change inside transaction
            $equipmentIds = [];
            if ($isLoan) {
                $equipmentIds = $data['equipment_ids'] ?? [];
                if (empty($equipmentIds)) {
                    throw new InvalidArgumentException(__('messages.services.service_order.equipment_required'));
                }

                // Pessimistic lock: block concurrent reads until this transaction commits
                $equipments = Equipment::whereIn('id', $equipmentIds)
                    ->lockForUpdate()
                    ->get();

                if ($equipments->count() !== count($equipmentIds)) {
                    throw new InvalidArgumentException(__('messages.services.service_order.equipment_not_found'));
                }

                foreach ($equipments as $equipment) {
                    if (!$equipment->isAvailableForLoan()) {
                        throw new EquipmentUnavailableException(
                            __('messages.services.service_order.equipment_not_available')
                        );
                    }
                    // Atomically mark as in_use before event listeners can fire
                    $equipment->markAsInUse();
                }
            }

            // 4. Create ServiceOrder (process is auto-generated by HasAutoReference)
            $serviceOrder = ServiceOrder::create([
                'client_id'          => $data['client_id'] ?? null,
                'client_location_id' => $data['client_location_id'] ?? null,
                'manager_id'         => $managerId,
                'location_id'        => $locationId,
                'service_type_id'    => $data['service_type_id'] ?? null,
                'workflow_type'      => $data['workflow_type'] ?? WorkflowType::STANDARD->value,
                'priority'           => $data['priority'] ?? null,
                'description'        => $data['description'] ?? null,
                'photo_path'         => $photoPath,
                'status'             => ServiceOrderStatus::PENDING->value,
            ]);

            // 5. Sync sectors (loan has no sectors)
            if (!$isLoan) {
                $sectorIds = $data['sector_ids'] ?? [];
                if (!empty($sectorIds)) {
                    $serviceOrder->sectors()->sync($sectorIds);

                    // 6. Auto-create one Task per sector
                    $sectors = Sector::whereIn('id', $sectorIds)->get();
                    foreach ($sectors as $sector) {
                        $task = Task::create([
                            'service_order_id' => $serviceOrder->id,
                            'manager_id'       => $managerId,
                            'name'             => $serviceOrder->process . ' - ' . $sector->name,
                            'description'      => $data['description'] ?? null,
                            'status'           => TaskStatus::PENDING->value,
                        ]);

                        $task->sectors()->sync([$sector->id]);
                    }
                }
            }

            // 7. Sync equipments (loan only)
            if ($isLoan && !empty($equipmentIds)) {
                $serviceOrder->equipments()->sync($equipmentIds);
            }

            ServiceOrderCreatedEvent::dispatch($serviceOrder);

            return $serviceOrder;
        });
    }
    public function update(ServiceOrder $serviceOrder, array $data): ServiceOrder
    {
        if (in_array($serviceOrder->status, [ServiceOrderStatus::COMPLETED->value, ServiceOrderStatus::CANCELLED->value])) {
            throw new InvalidArgumentException(__('messages.services.service_order.cannot_update_completed'));
        }
        return $this->transactions->execute(function () use ($serviceOrder, $data) {
            // Update the Location record separately — these fields are not on ServiceOrder.
            $this->updateLocation($serviceOrder, $data);

            // Only pass fillable service-order fields; location/relation keys are handled above.
            $soFields = collect($data)->except([
                'parish_id', 'street', 'reference_point', 'postal_code',
                'latitude', 'longitude', 'location_id',
                'sector_ids', 'equipment_ids',
            ])->toArray();

            $serviceOrder->update($soFields);

            if (array_key_exists('sector_ids', $data)) {
                $serviceOrder->sectors()->sync($data['sector_ids']);
            }

            if (array_key_exists('equipment_ids', $data)) {
                $serviceOrder->equipments()->sync($data['equipment_ids']);
            }

            return $serviceOrder;
        });
    }

    /**
     * Persist location fields (parish, street, coordinates …) to the related
     * Location record.  Creates a new Location and links it if none exists yet.
     */
    private function updateLocation(ServiceOrder $serviceOrder, array $data): void
    {
        // Map form field names → Location column names
        $fieldMap = [
            'parish_id'       => 'parish_id',
            'street'          => 'street_address',
            'reference_point' => 'landmark',
            'postal_code'     => 'postal_code',
            'latitude'        => 'latitude',
            'longitude'       => 'longitude',
        ];

        $locationData = [];
        foreach ($fieldMap as $formKey => $dbColumn) {
            if (!array_key_exists($formKey, $data)) {
                continue;
            }
            $val = $data[$formKey];
            if (in_array($formKey, ['street', 'reference_point']) && $val !== null) {
                $val = InputSanitizer::sanitize($val);
            }
            $locationData[$dbColumn] = $val;
        }

        if (empty($locationData)) {
            return;
        }

        $serviceOrder->loadMissing('location');

        if ($serviceOrder->location) {
            $serviceOrder->location->update($locationData);
        } else {
            $location = Location::create($locationData);
            $serviceOrder->update(['location_id' => $location->id]);
        }
    }
    public function cancel(ServiceOrder $serviceOrder): ServiceOrder
    {
        if ($serviceOrder->status === ServiceOrderStatus::COMPLETED->value) {
            throw new InvalidArgumentException(__('messages.services.service_order.cannot_cancel_completed'));
        }
        return $this->transactions->execute(function () use ($serviceOrder) {
            $serviceOrder->update(['status' => ServiceOrderStatus::CANCELLED->value]);
            $this->releaseEquipment($serviceOrder);
            return $serviceOrder;
        });
    }

    public function delete(ServiceOrder $serviceOrder): void
    {
        $this->transactions->execute(function () use ($serviceOrder) {
            $this->releaseEquipment($serviceOrder);
            $this->cancelCascade($serviceOrder);
            $serviceOrder->delete();
        });
    }

    /**
     * Cancel all open tasks, mini-tasks, and soft-delete non-approved work logs
     * that belong to a regular service order being deleted.
     */
    private function cancelCascade(ServiceOrder $serviceOrder): void
    {
        if ($serviceOrder->workflow_type === WorkflowType::LOAN) {
            return;
        }

        $taskIds = $serviceOrder->tasks()->pluck('id');

        if ($taskIds->isEmpty()) {
            return;
        }

        $miniTaskIds = MiniTask::whereIn('task_id', $taskIds)->pluck('id');

        if ($miniTaskIds->isNotEmpty()) {
            // Soft-delete work logs that are still in progress or awaiting review
            WorkLog::whereIn('mini_task_id', $miniTaskIds)
                ->whereIn('status', [WorkLogStatus::IN_PROGRESS->value, WorkLogStatus::SUBMITTED->value])
                ->each(fn(WorkLog $wl) => $wl->delete());

            // Cancel mini-tasks that are not already in a terminal state
            MiniTask::whereIn('task_id', $taskIds)
                ->whereNotIn('status', [MiniTaskStatus::COMPLETED->value, MiniTaskStatus::CANCELLED->value])
                ->update(['status' => MiniTaskStatus::CANCELLED->value]);
        }

        // Cancel tasks that are not already in a terminal state
        Task::where('service_order_id', $serviceOrder->id)
            ->whereNotIn('status', [TaskStatus::COMPLETED->value, TaskStatus::CANCELLED->value])
            ->update(['status' => TaskStatus::CANCELLED->value]);
    }

    /**
     * Return any IN_USE loaned equipment back to ACTIVE.
     * Called on cancel and delete so equipment is never left stranded.
     */
    private function releaseEquipment(ServiceOrder $serviceOrder): void
    {
        if ($serviceOrder->workflow_type !== WorkflowType::LOAN) {
            return;
        }

        $serviceOrder->loadMissing('equipments');

        foreach ($serviceOrder->equipments as $equipment) {
            if ($equipment->status === EquipmentStatus::IN_USE) {
                $equipment->markAsActive();
            }
        }
    }
    public function initiateReturn(ServiceOrder $serviceOrder): Task
    {
        // Guard pre-conditions before entering the transaction
        if ($serviceOrder->workflow_type !== WorkflowType::LOAN) {
            throw new InvalidArgumentException(__('messages.services.service_order.return_only_for_loan'));
        }

        if ($serviceOrder->tasks()->where('name', __('messages.task_names.equipment_return'))->exists()) {
            throw new InvalidArgumentException(__('messages.services.service_order.return_task_exists'));
        }

        $checkoutTask = $serviceOrder->tasks()
            ->where('name', __('messages.task_names.equipment_loan'))
            ->first();

        if (!$checkoutTask || $checkoutTask->status !== TaskStatus::COMPLETED->value) {
            throw new InvalidArgumentException(__('messages.services.service_order.checkout_must_complete'));
        }

        return $this->transactions->execute(function () use ($serviceOrder) {
            $task = Task::create([
                'service_order_id' => $serviceOrder->id,
                'manager_id'       => $serviceOrder->manager_id,
                'name'             => __('messages.task_names.equipment_return'),
                'status'           => TaskStatus::PENDING->value,
            ]);

            $task->load(['sectors', 'manager']);
            return $task;
        });
    }

    public function complete(ServiceOrder $serviceOrder): ServiceOrder
    {
        if ($serviceOrder->status === ServiceOrderStatus::COMPLETED->value) {
            throw new InvalidArgumentException(__('messages.services.service_order.already_completed'));
        }
        $hasIncompleteTasks = $serviceOrder->tasks()
            ->where('status', '!=', TaskStatus::COMPLETED->value)
            ->exists();
        if ($hasIncompleteTasks) {
            throw new InvalidArgumentException(__('messages.services.service_order.incomplete_tasks'));
        }
        return $this->transactions->execute(function () use ($serviceOrder) {
            $serviceOrder->update(['status' => ServiceOrderStatus::COMPLETED->value]);

            // Spec §3.3: equipment returns to active when the loan SO is completed (in_use → active)
            if ($serviceOrder->workflow_type === WorkflowType::LOAN && $serviceOrder->relationLoaded('equipments')) {
                foreach ($serviceOrder->equipments as $equipment) {
                    $equipment->markAsActive();
                }
            }

            ServiceOrderCompletedEvent::dispatch($serviceOrder);
            return $serviceOrder;
        });
    }
}