<?php
namespace App\Features\ServiceOrders\Services;
use App\Core\Enums\MiniTaskStatus;
use App\Core\Enums\ServiceOrderStatus;
use App\Core\Enums\TaskStatus;
use App\Core\Enums\WorkLogStatus;
use App\Core\Helpers\InputSanitizer;
use App\Core\Services\TransactionHandler;
use App\Features\Locations\Models\Location;
use App\Features\MiniTasks\Models\MiniTask;
use App\Features\ServiceOrders\Events\ServiceOrderCompletedEvent;
use App\Features\ServiceOrders\Events\ServiceOrderCreatedEvent;
use App\Features\ServiceOrders\Jobs\ScanServiceOrderPhoto;
use App\Features\ServiceOrders\Models\ServiceOrder;
use App\Features\Tasks\Models\Task;
use App\Features\WorkLogs\Models\WorkLog;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Cache;
use InvalidArgumentException;
class ServiceOrderService
{
    public function __construct(
        private TransactionHandler $transactions,
    ) {}
    
    public function create(array $data, string $managerId, ?string $createdById = null): ServiceOrder
    {
        return $this->transactions->execute(function () use ($data, $managerId, $createdById) {
            // 1. Create Location
            $locationId = null;
            if (!empty($data['parish_id'])) {
                $location = Location::create([
                    'parish_id'       => $data['parish_id'],
                    'postal_code'     => $data['postal_code'] ?? '',
                    'street_address'  => InputSanitizer::sanitize($data['street'] ?? ''),
                    'landmark'        => isset($data['reference_point']) ? InputSanitizer::sanitize($data['reference_point']) : '',
                    'latitude'        => $data['latitude'] ?? null,
                    'longitude'       => $data['longitude'] ?? null,
                ]);
                $locationId = $location->id;
            }

            // 2. Handle photo upload
            $photoPath = null;
            if (isset($data['photo']) && $data['photo'] instanceof UploadedFile) {
                $photoPath = $data['photo']->store('service-orders', 'public');
            }

            // 3. Create ServiceOrder (process is auto-generated by HasAutoReference)
            $serviceOrder = ServiceOrder::create([
                'client_id'          => $data['client_id'] ?? null,
                'client_location_id' => $data['client_location_id'] ?? null,
                'manager_id'         => $managerId,
                'created_by'         => $createdById,
                'location_id'        => $locationId,
                'service_type_id'    => $data['service_type_id'] ?? null,
                'priority'           => $data['priority'] ?? null,
                'description'        => $data['description'] ?? null,
                'photo_path'         => $photoPath,
                'start_date'         => $data['start_date'],
                'end_date'           => $data['end_date'],
                'status'             => ServiceOrderStatus::PENDING->value,
            ]);

            // 4. Sync sectors (Tasks are created on activate, not on create)
            $sectorIds = $data['sector_ids'] ?? [];
            if (!empty($sectorIds)) {
                $serviceOrder->sectors()->sync($sectorIds);
            }

            ServiceOrderCreatedEvent::dispatch($serviceOrder);

            if ($photoPath) {
                ScanServiceOrderPhoto::dispatch(
                    $serviceOrder->id,
                    $photoPath,
                    $createdById,
                );
            }

            return $serviceOrder;
        });
    }
    public function activate(ServiceOrder $serviceOrder): ServiceOrder
    {
        return $this->transactions->execute(function () use ($serviceOrder) {
            $fresh = ServiceOrder::lockForUpdate()->findOrFail($serviceOrder->id);

            if ($fresh->status !== ServiceOrderStatus::PENDING) {
                throw new InvalidArgumentException(__('messages.services.service_order.cannot_activate_non_pending'));
            }

            $existingSectorIds = $fresh->tasks()
                ->with('sectors')
                ->get()
                ->flatMap(fn(Task $t) => $t->sectors->pluck('id'))
                ->all();

            $sectors = $fresh->sectors()
                ->whereNotIn('sectors.id', $existingSectorIds)
                ->get();

            foreach ($sectors as $sector) {
                $task = Task::create([
                    'service_order_id' => $fresh->id,
                    'manager_id'       => $fresh->manager_id,
                    'description'      => $fresh->process . ' - ' . $sector->name,
                    'status'           => TaskStatus::PENDING->value,
                ]);
                $task->sectors()->sync([$sector->id]);
            }

            $fresh->update(['status' => ServiceOrderStatus::IN_PROGRESS->value]);

            Cache::tags(["user:{$fresh->manager_id}"])->flush();
            return $fresh;
        });
    }

    public function update(ServiceOrder $serviceOrder, array $data): ServiceOrder
    {
        if ($serviceOrder->status === ServiceOrderStatus::COMPLETED || $serviceOrder->status === ServiceOrderStatus::CANCELLED) {
            throw new InvalidArgumentException(__('messages.services.service_order.cannot_update_completed'));
        }
        return $this->transactions->execute(function () use ($serviceOrder, $data) {
            // Update the Location record separately — these fields are not on ServiceOrder.
            $this->updateLocation($serviceOrder, $data);

            // Only pass fillable service-order fields; location/relation keys are handled above.
            $soFields = collect($data)->except([
                'parish_id', 'street', 'reference_point', 'postal_code',
                'latitude', 'longitude', 'location_id',
                'sector_ids', 'photo',
            ])->toArray();

            $newPhotoPath = null;
            if (isset($data['photo']) && $data['photo'] instanceof UploadedFile) {
                $newPhotoPath = $data['photo']->store('service-orders', 'public');
                $soFields['photo_path'] = $newPhotoPath;
            }

            $serviceOrder->update($soFields);

            if (array_key_exists('sector_ids', $data)) {
                $this->syncSectors($serviceOrder, $data['sector_ids']);
            }

            if ($newPhotoPath) {
                ScanServiceOrderPhoto::dispatch(
                    $serviceOrder->id,
                    $newPhotoPath,
                    $serviceOrder->created_by,
                );
            }

            return $serviceOrder;
        });
    }

    /**
     * Persist location fields (parish, street, coordinates …) to the related
     * Location record.  Creates a new Location and links it if none exists yet.
     */
    private function updateLocation(ServiceOrder $serviceOrder, array $data): void
    {
        // Map form field names → Location column names
        $fieldMap = [
            'parish_id'       => 'parish_id',
            'street'          => 'street_address',
            'reference_point' => 'landmark',
            'postal_code'     => 'postal_code',
            'latitude'        => 'latitude',
            'longitude'       => 'longitude',
        ];

        $locationData = [];
        foreach ($fieldMap as $formKey => $dbColumn) {
            if (!array_key_exists($formKey, $data)) {
                continue;
            }
            $val = $data[$formKey];
            if (in_array($formKey, ['street', 'reference_point']) && $val !== null) {
                $val = InputSanitizer::sanitize($val);
            }
            $locationData[$dbColumn] = $val;
        }

        if (empty($locationData)) {
            return;
        }

        $serviceOrder->loadMissing('location');

        if ($serviceOrder->location) {
            $serviceOrder->location->update($locationData);
        } else {
            $location = Location::create($locationData);
            $serviceOrder->update(['location_id' => $location->id]);
        }
    }

    private function syncSectors(ServiceOrder $serviceOrder, array $incomingSectorIds): void
    {
        $currentSectorIds = $serviceOrder->sectors()->pluck('id')->all();

        $removedSectorIds = array_diff($currentSectorIds, $incomingSectorIds);

        if (!empty($removedSectorIds)) {
            $hasTaskForRemoved = Task::where('service_order_id', $serviceOrder->id)
                ->whereHas('sectors', fn($q) => $q->whereIn('sectors.id', $removedSectorIds))
                ->exists();

            if ($hasTaskForRemoved) {
                throw new InvalidArgumentException(
                    __('messages.services.service_order.cannot_remove_sector_with_tasks')
                );
            }
        }

        $serviceOrder->sectors()->sync($incomingSectorIds);

        $newSectorIds = array_diff($incomingSectorIds, $currentSectorIds);

        $canAutoCreate = in_array($serviceOrder->status, [
            ServiceOrderStatus::IN_PROGRESS,
            ServiceOrderStatus::AWAITING_APPROVAL,
        ]);

        if (!empty($newSectorIds) && $canAutoCreate) {
            $newSectors = $serviceOrder->sectors()->whereIn('sectors.id', $newSectorIds)->get();

            foreach ($newSectors as $sector) {
                $task = Task::create([
                    'service_order_id' => $serviceOrder->id,
                    'manager_id'       => $serviceOrder->manager_id,
                    'description'      => $serviceOrder->process . ' - ' . $sector->name,
                    'status'           => TaskStatus::PENDING->value,
                ]);
                $task->sectors()->sync([$sector->id]);
            }
        }
    }

    public function markAwaitingApproval(ServiceOrder $serviceOrder): ServiceOrder
    {
        return $this->transactions->execute(function () use ($serviceOrder) {
            $serviceOrder->update(['status' => ServiceOrderStatus::AWAITING_APPROVAL->value]);
            Cache::tags(["user:{$serviceOrder->manager_id}"])->flush();
            return $serviceOrder;
        });
    }

    public function cancel(ServiceOrder $serviceOrder): ServiceOrder
    {
        if ($serviceOrder->status === ServiceOrderStatus::COMPLETED) {
            throw new InvalidArgumentException(__('messages.services.service_order.cannot_cancel_completed'));
        }
        if ($serviceOrder->status === ServiceOrderStatus::AWAITING_APPROVAL) {
            throw new InvalidArgumentException(__('messages.services.service_order.cannot_cancel_awaiting_approval'));
        }
        return $this->transactions->execute(function () use ($serviceOrder) {
            $serviceOrder->update(['status' => ServiceOrderStatus::CANCELLED->value]);
            Cache::tags(["user:{$serviceOrder->manager_id}"])->flush();
            return $serviceOrder;
        });
    }

    public function delete(ServiceOrder $serviceOrder): void
    {
        $this->transactions->execute(function () use ($serviceOrder) {
            $this->cancelCascade($serviceOrder);
            $serviceOrder->delete();
        });
    }

    /**
     * Cancel all open tasks, mini-tasks, and soft-delete non-approved work logs.
     */
    private function cancelCascade(ServiceOrder $serviceOrder): void
    {
        $taskIds = $serviceOrder->tasks()->pluck('id');

        if ($taskIds->isEmpty()) {
            return;
        }

        $miniTaskIds = MiniTask::whereIn('task_id', $taskIds)->pluck('id');

        if ($miniTaskIds->isNotEmpty()) {
            WorkLog::whereIn('mini_task_id', $miniTaskIds)
                ->whereIn('status', [WorkLogStatus::IN_PROGRESS->value, WorkLogStatus::SUBMITTED->value])
                ->each(fn(WorkLog $wl) => $wl->delete());

            MiniTask::whereIn('task_id', $taskIds)
                ->whereNotIn('status', [MiniTaskStatus::COMPLETED->value, MiniTaskStatus::CANCELLED->value])
                ->update(['status' => MiniTaskStatus::CANCELLED->value]);
        }

        Task::where('service_order_id', $serviceOrder->id)
            ->whereNotIn('status', [TaskStatus::COMPLETED->value, TaskStatus::CANCELLED->value])
            ->update(['status' => TaskStatus::CANCELLED->value]);
    }

    public function complete(ServiceOrder $serviceOrder): ServiceOrder
    {
        if ($serviceOrder->status !== ServiceOrderStatus::AWAITING_APPROVAL) {
            throw new InvalidArgumentException(__('messages.services.service_order.cannot_complete_not_awaiting_approval'));
        }
        $hasIncompleteTasks = $serviceOrder->tasks()
            ->where('status', '!=', TaskStatus::COMPLETED->value)
            ->exists();
        if ($hasIncompleteTasks) {
            throw new InvalidArgumentException(__('messages.services.service_order.incomplete_tasks'));
        }
        return $this->transactions->execute(function () use ($serviceOrder) {
            $serviceOrder->update(['status' => ServiceOrderStatus::COMPLETED->value]);
            ServiceOrderCompletedEvent::dispatch($serviceOrder);
            Cache::tags(["user:{$serviceOrder->manager_id}"])->flush();
            return $serviceOrder;
        });
    }
}